language: cpp
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - ninja-build
    - python2.7
    - git
    - perl
    - libx11-xcb-dev
    - libglu1-mesa-dev
    - libxrender-dev
    - libxi-dev
    - libasound2-dev
    - libgstreamer-plugins-base0.10-dev
branches:
    only:
        - fw4spl_0.10.2
compiler:
  - gcc

before_script:
  - git clone https://gist.github.com/f6148aa0366124d930c5.git script_sh
  - chmod a+x script_sh/cmd-travis.sh
  - git clone https://gist.github.com/aa8c2b4ca1cab41dc267.git script_py
  - chmod a+x script_py/clean-cmake-build.py
  - git clone https://gist.github.com/a3ba75b69234af2e3c0e.git upload_script
  - chmod a+x upload_script/travis-upload.sh
  - wget -q http://www.cmake.org/files/v3.3/cmake-3.3.0-Linux-x86_64.tar.gz -O /tmp/cmake-3.3.0-Linux-x86_64.tar.gz
  - tar -xvf /tmp/cmake-3.3.0-Linux-x86_64.tar.gz > /dev/null
  - rm -rf /tmp/cmake-3.3.0-Linux-x86_64.tar.gz
  - export PATH=$PWD/cmake-3.3.0-Linux-x86_64/bin/:$PATH
  - mkdir install
  - mkdir build
  - cd $TRAVIS_BUILD_DIR/build
  - cmake $TRAVIS_BUILD_DIR -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/install -DCMAKE_BUILD_TYPE=Debug -DARCHIVE_DIR=/tmp/archive

script: 
  - $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make jpeg/fast jpeg.log
  - python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/jpeg
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make zlib/fast zlib.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/zlib
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make tiff/fast tiff.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/tiff
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make libpng/fast libpng.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/png
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make libiconv/fast libiconv.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/libiconv
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make libxml/fast libxml.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/libxml
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make expat/fast expat.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/expat
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make python/fast python.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/python
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make boost/fast boost.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/boost
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make freetype/fast freetype.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/freetype
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make icu4c/fast icu4c.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/icu4c
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make numpy/fast numpy.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/numpy
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make qt/fast qt.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/qt
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make vtk/fast vtk.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/vtk
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make vxl/fast vxl.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/vxl
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make gdcm/fast gdcm.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/gdcm
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make itk/fast itk.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/itk
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make camp/fast camp.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/camp
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make cppunit/fast cppunit.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/cppunit
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make ann/fast ann.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/ann
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make dcmtk/fast dcmtk.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/dcmtk
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make cryptopp/fast cryptopp.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/cryptopp
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make tetgen/fast tetgen.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/tetgen
  #- $TRAVIS_BUILD_DIR/script_sh/cmd-travis.sh make json-spirit/fast json-spirit.log
  #- python $TRAVIS_BUILD_DIR/script_py/clean-cmake-build.py $TRAVIS_BUILD_DIR/build/json-spirit
  
after_script:
  - rm -rf /tmp/archive
  - rm -rf $TRAVIS_BUILD_DIR/build
  - tar -zcvf fw4spl_0.10.2-deps.tar.gz $TRAVIS_BUILD_DIR/install
  - $TRAVIS_BUILD_DIR/upload_script/travis-upload.sh fw4spl_0.10.2-deps.tar.gz
