language: cpp
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - ninja-build
    - python2.7
    - git
    - perl
    - libx11-xcb-dev
    - libglu1-mesa-dev
    - libxrender-dev
    - libxi-dev
    - libasound2-dev
    - libgstreamer-plugins-base0.10-dev
branches:
    only:
        - fw4spl_0.10.2
compiler:
  - gcc

before_script:
  - git clone https://gist.github.com/f6148aa0366124d930c5.git script
  - chmod a+x script/make-travis.sh
  - wget -q http://www.cmake.org/files/v3.3/cmake-3.3.0-Linux-x86_64.tar.gz -O /tmp/cmake-3.3.0-Linux-x86_64.tar.gz
  - tar -xvf /tmp/cmake-3.3.0-Linux-x86_64.tar.gz > /dev/null
  - export PATH=$PWD/cmake-3.3.0-Linux-x86_64/bin/:$PATH
  - mkdir install
  - mkdir build
  - cd $TRAVIS_BUILD_DIR/build
  - cmake $TRAVIS_BUILD_DIR -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/install -DCMAKE_BUILD_TYPE=Debug

script: $TRAVIS_BUILD_DIR/script/make-travis.sh
